name: Build and Deploy TEE Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t your-image-name .
          docker push your-image-name

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image to GCR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/flare-social-agent:latest

      - name: Deploy to Confidential Computing VM
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: flare-social-agent
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/flare-social-agent:latest
          region: us-central1
          platform: managed
          confidential: true
          flags: --machine-type=n2d-standard-2


