name: Build and Deploy TEE Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/flare-social-agent:latest
        
    - name: Deploy to Confidential Computing VM
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: flare-social-agent
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/flare-social-agent:latest
        region: us-central1
        platform: managed
        confidential: true
        flags: --machine-type=n2d-standard-2
       
        
